### ISSUE TITLE
XML Mark up and Check point 3

### ISSUE THREAD

**Issue by JakeCode121** [JakeCode121/Washington_Trail#11]
Hello, I have been working on our XML; there are still large portions that aren't marked as far as date, time, places, and so on.  I'm going to keep working on this.  I loaded the most recent version I have a t 1:21PM.  Let me know if anyone wants to take the lead on the new portions of checkpoint 3.  I've been messing with it, but it is not clear to me.  I'm sure it will get cleared up in class today.

Take care,

 Jake
@haggis78 @Bennediction @mld137 @dsl28

**Comment by cozyycoding** [comment]
@mld137 @dsl28 If you could work on the XML and the schema to help prepare it for Project Checkpoint 3, that would be much appreciated.

**Comment by dsl28** [comment]
Sure thing! @Bennediction @mld137! Also, @JakeCode121, could you push a file with the needed coordinates for locations? You know the most about the subject, and I want to ensure that they’re accurate.

**Comment by JakeCode121** [comment]
@dsl28 @mld137 @Bennediction 

Fort Le Boeuf
41.9400 N
79.9822 W

Fort Venango

41.3890 N
79.8222 W
