### ISSUE TITLE
Help... XPATH!

### ISSUE THREAD

**Issue by JakeCode121** [JakeCode121/Washington_Trail#14]
Well I forget how to narrow to specific names.

I ran this  /journal//person/@last.   and I got numerous names.... How do I get just one time instead of numerous.  

I love coding

@haggis78 @Bennediction @dsl28 @mld137

**Comment by cozyycoding** [comment]
Hey Jake, I think I'm kind of confused as to what you're asking. 
```//person/@last```
 will get you every time that the last name tag is used. If you're looking for every distinct last name, you'll want to use 
```distinct-values(//person/@last)```. 
Hope this helps!

@JakeCode121

**Comment by JakeCode121** [comment]
@Bennediction 
 
I will get Washington 15 times.. I only want it once to help me with my schema

**Comment by cozyycoding** [comment]
You'll want to use the distinct values function to only get Washington once.
 ```distinct-values(//person/@last)``` 
should work
@JakeCode121

**Comment by JakeCode121** [comment]
@Bennediction Thank you

**Comment by cozyycoding** [comment]
Anytime, thanks for reaching out!
