### ISSUE TITLE
Updates, I have made updates to XML and the RNC, per our conversation. 

### ISSUE THREAD

**Issue by JakeCode121** [JakeCode121/Washington_Trail#15]
Hi all, 

If you wouldn't mind looking at the RNC.  To see if it is on the right track... Thanks

@haggis78 @Bennediction @mld137 @dsl28 

Sincerely,
@JakeCode121

**Comment by haggis78** [comment]
@JakeCode121 Here are a few things I see:
-What goes inside the element "intro"? Not defined here. Ditto "people", "place", "entry".
-You have a definition line for the element person, but you don't have a "parent line" that says what other element might contain a person element.
-Also in the person element, you've listed full names of people, but that's not how the program will read them. You need to tell it to expect a certain set of attributes plus text.
-For the attribute definitions, where you have (for example) rank = attribute {...}, you need rank = attribute **rank** {...}.
-For the attribute values you have listed, you've generally used the plus or splat operators; in some cases at least you probably want the | pipe operator.
