### ISSUE TITLE
Office Hours This Weekend

### ISSUE THREAD

**Issue by cozyycoding** [JakeCode121/Washington_Trail#16]
Hey everyone, @dsl28 @JakeCode121 @mld137 

I have office hours Sunday at 2 pm if anybody needs help with the homework or with the project code or anything. I can also move my hours around if the timings inconvenient.

Thanks,

Ben

**Comment by JakeCode121** [comment]
Sounds Good I’ll be there

Sincerely,

Jake


Jacob A. Snyder
Class of 2021
History Major; PS Minor
Pitt-Greensburg Veteran Student Mentor
Jas611@pitt.edu<mailto:Jas611@pitt.edu>
724-771-6401
