### ISSUE TITLE
HTML documents placed on server

### ISSUE THREAD

**Issue by JakeCode121** [JakeCode121/Washington_Trail#24]
Hello, @haggis78 @Bennediction 

I went to office hours.  I believe that I placed everything on the server; however, nothing is populating on the washtrail.newtfire.org website

<img width="1423" alt="Screen Shot 2020-11-17 at 4 18 06 PM" src="https://user-images.githubusercontent.com/69920748/99451841-ce19ee00-28f0-11eb-81cf-1e993655ff3a.png">

I hope you can see my screen shot 

sincerely,

@JakeCode121 

fyi @mld137 @dsl28

**Comment by smdunn921** [comment]
Hey @JakeCode121 ! I was actually in the midst of making an issue for you guys about this! I believe the issue is due to the capitalization of letters in the filenames, especially in the index.html. You'll want the first letter of this to be lowercase. The index.html especially *needs* to be this way, but it would be a good idea to change the others that are like this as well. After that, you can reupload them via filezilla and see if that remedies anything

**Comment by JakeCode121** [comment]
@smdunn921 it didn't populate immediately.  I will check back.

**Comment by smdunn921** [comment]
@JakeCode121 i don't know if it's correct or not but im looking on filezilla and 1) it looks like you uploaded *everything* from github onto there in a folder and the other capitalized files are still there. you'll have to delete the capitalized ones from the server and i don't know if the Washington_Trail folder from github was put up there on purpose, but all you really need up are the html and css files (and any pictures if you have them)

**Comment by smdunn921** [comment]
@JakeCode121 okay now that you've deleted all the other capitalized files, i think the one last thing you need to do that'll hopefully get this up and running is reupload the index.html– it looks like the file that's up right now is the "welcome to newtfire" splash page that's up, so if you reupload your index.html to overwrite it, that will hopefully be the finale

**Comment by smdunn921** [comment]
@JakeCode121 for whatever reason, it looks like the index you put up is somehow still the file for the splash page already in place rather than the project's index page

**Comment by haggis78** [comment]
@JakeCode121 Hooray -- it's visible now! Obviously there's more to do, but you now well and truly have a project website. @smdunn921 Thanks for your help getting this up. I hadn't spotted the capitalized file names.

**Comment by JakeCode121** [comment]
Thank you both!!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by JakeCode121** [comment]
@smdunn921 

Thanks for your help.  I messed around with it, and it looks like a page.

**Comment by smdunn921** [comment]
Yay! I'm glad it's up and getting there! Good work! 🥳
