### ISSUE TITLE
Weekly meeting 

### ISSUE THREAD

**Issue by JakeCode121** [JakeCode121/Washington_Trail#3]
Hello all, 

What is the best time for all of us to meet?  I'm operating primarily from home, so Zoom is good for me @dsl28 @haggis78 @mld137 @Bennediction

**Comment by dsl28** [comment]
Really, I’m pretty flexible in my schedule. Any day of the week, I’m done by four in the afternoon, if something needs to be earlier in the day, I’d say that Monday, Wednesday or Friday would be best, since I have 9-3 open.

**Comment by mld137** [comment]
I'm free till 2 most days

**Comment by haggis78** [comment]
I can generally do MWF between noon and 2 PM. If we were to set up a meeting for Monday, would others be free during that window? @JakeCode121 @mld137 @dsl28 @Bennediction

**Comment by dsl28** [comment]
Yeah! That works for me.

**Comment by cozyycoding** [comment]
That works for me

**Comment by mld137** [comment]
Yes, that works for me.

**Comment by haggis78** [comment]
OK, I set up a recurring weekly Zoom meeting in Canvas for noon each Monday. You'll find it under the Zoom link, clearly labeled. Zoom is now going to require all sessions to have either a waiting room or a passcode; I made the passcode "digital", which is the same as that for our class meetings. But I think that if you go through Canvas, it goes around that.

It hadn't been clear who was going to set up the meeting, so I guess there isn't one for this week. But it would be a good idea to go ahead and start talking here on Github Issues about what you see as the purpose and major components of the project, as well as continuing to compile source material. @JakeCode121, could you share some ideas about things that @dsl28 and @mld137 could be working on? For example, if you think that you'd like to include transcriptions of the blue historical markers, someone could be typing them up in an xml file. You can worry later about what the markup will be.

Also, @Bennediction and I were talking last week about JavaScript, at which he's quite adept, and if you want to include a clickable map, that will be the way to go.

**Comment by JakeCode121** [comment]
Sounds good, thank you Dr. Campbell; I just got all of the zoom links in Canvas.
