### ISSUE TITLE
New Page!

### ISSUE THREAD

**Issue by JakeCode121** [JakeCode121/Washington_Trail#30]
Hi everyone

I created a new page called Photos on the trail.. It is the Pics I took on my way from Pitts to Erie

@haggis78 @Bennediction @mld137 @dsl28

**Comment by haggis78** [comment]
@JakeCode121 it looks good, though oddly there are some blank spots. Anyway, will there be some way to link this with other aspect of the site? I think that overall there are some missing opportunities for cross-linking that would make the site more interactive, interesting, and useful. For example, under the description of each fort that can be called up in the Map page, it would be great to have a link that takes the user directly to the spot in the journal where entries relating to that location are found.
